#%RAML 1.0 Trait
description: This is header trait.
headers:
  client_id:
    minLength: 10
    maxLength: 20
    type: string
    required: true
  client_secret:
    minLength: 10
    maxLength: 20
    type: string
    required: true